{% set name = "cryoswath" %}
{% set version = "0.2.6" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cryoswath-{{ version }}.tar.gz
  sha256: 8f75b093908b889e73916331cc14c8ea442b5388753cc567cd52a6ba723de9ca

build:
  entry_points:
    - cryoswath-init = cryoswath.misc:init_project_cli
    - cryoswath-download-rgi = cryoswath.misc:download_rgi_cli
    - cryoswath-update-keyring = cryoswath.misc:update_keyring_cli
    - cryoswath-update-netrc = cryoswath.misc:update_netrc_cli
    - cryoswath-update-tracks = cryoswath.misc:update_track_database_cli
    - cryoswath = cryoswath.misc:cryoswath_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - dask-core
    - defusedxml
    - earthaccess >=0.18
    - geopandas >=1.0.1
    - gitpython
    - h5netcdf
    - h5py
    - keyring
    - matplotlib-base
    - numpy
    - packaging
    - pandas >=2,<3
    - pyarrow
    - pyogrio
    - pyproj
    - pystac-client
    - pytables
    - python-dateutil
    - rasterio
    - rioxarray
    - scikit-learn
    - scipy
    - shapely
    - stackstac
    - statsmodels
    - tqdm
    - xarray >=2025.3
    - zarr

test:
  imports:
    - cryoswath
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/j-haacker/cryoswath
  summary: Swath processing toolbox for CryoSat-2
  description: |
    cryoswath is a python package containing processing pipelines, a tool
    library, and some pre-assembled data to retrieve and study CryoSat-2
    data.
    Adaptability lies at its core. The user can access many options simply
    by passing arguments to functions; everything else can be customized
    changing the concerned function or adding a new one.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://cryoswath.readthedocs.io/

extra:
  recipe-maintainers:
    - j-haacker
